# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2.1

defaults: &defaults
  working_directory: ~/flexmart-store
  docker:
    - image: circleci/php:7.4.6-node-browsers

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: sudo apt update # PHP CircleCI 2.0 Configuration File# PHP CircleCI 2.0 Configuration File sudo apt install zlib1g-dev libsqlite3-dev
      - run: sudo docker-php-ext-install zip
      - restore_cache:
          key: flexmart-store-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - composer-v1-{{checksum "composer.lock"}}
            - composer-v1-
      - run:
          name: "Install Composer Package"
          command: composer install -n --prefer-dist
      - save_cache:
          key: flexmart-store-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/flexmart-store
      - save_cache:
          key: composer-v1-{{checksum "composer.lock"}}
          paths:
            - vendor
      - run:
          name: "Copy ENV"
          command: "cp .env.testing .env"
      - run:
          name: "Run PHP Unit Test"
          command: "./vendor/bin/phpunit"
      - run:
          name: "Upload to codecov"
          command: "bash <(curl -s https://codecov.io/bash)"
